### ISSUE TITLE
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block.

### ISSUE THREAD

**Issue by jaswanthkar** [feludwig/pgsql2osm#1]
INFO: detected middle database layout: legacy text[]
[ 1/5 start    ] 2023-11-01_17:08:26
[ 2/5 within   ] public.berlin_point row 907159 / 907159      100.0%
[ 2/5 within   ] 907159 nodes within bounds
[ 2/5 within   ] public.berlin_polygon row 637792 / 637792      100.0%
[ 2/5 within   ] 632435 ways, 4931 rels from public.berlin_polygon
[ 2/5 within   ] public.berlin_line row 427682 / 427682      100.0%
[ 2/5 within   ] 1042324 ways, 6516 rels within bounds
[ 3/5 children ] 3 nodes, 13540 ways, 0 rels children of rel 6516 / 6516      100.0%
[ 3/5 children ] 8365309 nodes children of way 1051796 / 1051796      100.0%
[ 4/5 parents  ] checking parent ways of 907159 nodes
Traceback (most recent call last):
  File "/home/jaswanth/Desktop/SouthIndia/Package/pgsql2osm.py", line 1202, in <module>
    s.main()
  File "/home/jaswanth/Desktop/SouthIndia/Package/pgsql2osm.py", line 306, in main
    t=asyncio.run(stream_osm_xml(self))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jaswanth/Desktop/SouthIndia/Package/pgsql2osm.py", line 698, in stream_osm_xml
    nodes_parent_wr(s,a,only_nodes_within=True)
  File "/home/jaswanth/Desktop/SouthIndia/Package/pgsql2osm.py", line 514, in nodes_parent_wr
    for node_c,way_ids,rel_ids in a.g_adaptive_parent_multiquery(nodes_name,s.c,
  File "/home/jaswanth/Desktop/SouthIndia/Package/pgsql2osm.py", line 52, in g_adaptive_parent_multiquery
    c.execute("SET statement_timeout='30s';")
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block.

Changed the timeout also, but getting the same error. Can you provide any assistance.

**Comment by feludwig** [comment]
Hello!
1) can you please try again with the latest version (`git pull`)
2) Can you also provide the command line arguments ?
3) I'm thinking you may not have all tables in the database: do `berlin_ways` and `berlin_rels` exist ?
4) What do you mean with the issue name ?
If it still errors out, please try `with_parents=False` (on line 688)

The statement timeout is only a mechanism to detect the optimal array length to use in the index lookup, making it longer could actually take much more time in total (if you're changing the one that has a value of `1s` lines 65 and 136)

**Comment by feludwig** [comment]
what was the problem/how did you solve it ?
Also, which version of osm2pgsql and which options did you use when importing the database ?

**Comment by jaswanthkar** [comment]
Everything is working fine, I have been using 1.9.2 version on ubuntu. The problem is with the cursor, so befor line number 54, I have initialized the cursor again c = pyscopg2.connect().cursor(). All the tables are present inside the db.

**Comment by jaswanthkar** [comment]
The process is slow on my machine, berlin is a small place but the flatnodes file is of 83GB. Is there any way to increase the speed.

**Comment by feludwig** [comment]
The flatnodes is by design only for big extracts (continent, planet). If you only need osm data for berlin, maybe check out geofabrik downloads: they provide small extracts.
For extracting from the database, maybe tune some of its parameters (`SHOW shared_buffers;`, `maintenance_work_mem`, `work_mem` etc...) And how much ram do you have ? pgsql2osm can use up to 5-10x of the osm output size in addition to the database
And are you using an ssd or a harddrive ? The database is much slower on a harddrive, and the flatnodes lookups will be as well

**Comment by jaswanthkar** [comment]
I am on 16gb ram and HDD of 1Tb (Don't Laugh). I have this berlin-latest.osm.pbf file, i have used it with osm2pgsql to generate the database with --flat-nodes. But the --flat-nodes file is of 83.3gb. I am newbiew for this stuff, where can i find the small extracts.  I am currently on https://download.geofabrik.de/europe/germany/berlin.html. For precise can we directly convert the pgsql data to osm without the flatnodes file, since I have added some data into pgsql after the initial database built using osm2pgsql. I need to convert all this data into osm.pbf file again. Sorry for taking your time, but if possible please help me on this. Thanks in advance.

**Comment by feludwig** [comment]
Oh you have an interesting usecase :)
Yes, if you have custom data (cannot just download geofabrik) and without an ssd it will take a long time. maybe increase the database's work_mem and maintenance_work_mem to about 200MB (or more if the 16GB are not all too used up). Also shared_buffers: if it's the default 4GB try with 6GB
But the harddirve is what is slowing you down, even on a 300MB/s peak hdd I had the database noticeably slower because random IOPS are 10MB/s typically and that's the important part. With one of the fancy ssds (expensive but solid random iops) you can reach 50-200MB/s...

About the flatnodes file, I think you can also osm2pgsql-import without it and then make pgsql2osm read from the `_nodes` table. But that's unsupported for now because I didn't set up multiple databases; it should work in theory (make sure ALL nodes data is in _nodes table, then just give pgsql2osm get_lonlat_bin=/bin/true and flatnodes_file=/dev/null) and it would require you to reimport...

**Comment by jaswanthkar** [comment]
Thank you for your time and patience. That was an insightful interaction.

**Comment by feludwig** [comment]
Depending on your additional data, if it's not geometric features but only tags changes, you can simply parse the osm xml
* osmium convert .osm.pbf to .osm,
* (maybe python script) something to read xml, fetch id from database and if modified data: add to xml,
* write out xml to .osm,
* omsium check-refs for good measure
* osmium sort .osm output=.osm.pbf

**Comment by jaswanthkar** [comment]
Can you share your Linkedin or some other social media. So that I can explain my usecase clearly.

**Comment by feludwig** [comment]
email fludwig@student.ethz.ch
